name: barahi
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  auto_validating_text_field: ^0.1.4
  flutter_facebook_login: ^3.0.0
  esewa_pnp: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
